version: '3'

services:
  pizzaria:
    build: .
    restart: always
    command: sh -c "sh start.sh"
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
      - rabbit.env
    ports:
      - 80:8000
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - backend

  adminer-db:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.12.0-management-alpine
    env_file:
      - rabbit.env
    ports:
      - 15672:15672
    networks:
      - backend
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq:

networks:
  backend:
