# Generated by Django 4.2.1 on 2023-05-09 23:24

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to=polls.models.category_file_path)),
            ],
        ),
    ]
