# Generated by Django 4.2.1 on 2023-05-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_employee_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('employees', models.ManyToManyField(to='polls.employee')),
                ('paths', models.ManyToManyField(to='polls.paths')),
            ],
        ),
    ]
