# Generated by Django 4.2.1 on 2023-05-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Placed'), (2, 'Processing'), (3, 'Completed')], default=1),
        ),
    ]
