# Generated by Django 4.2.1 on 2023-05-09 23:33

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(upload_to=polls.models.product_file_path)),
                ('status', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='products', to='polls.category')),
            ],
        ),
    ]
