# Generated by Django 4.2.1 on 2023-05-10 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='group',
            name='paths',
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Paths',
        ),
    ]
