# Generated by Django 4.2.1 on 2023-05-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_product_categories_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='polls.product'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='polls.client', unique=True)),
                ('products', models.ManyToManyField(to='polls.product')),
            ],
        ),
    ]
